### DISCUSSION TITLE
Customizing documentation of  a python module

### DISCUSSION THREAD

**Discussion by ecomodeller** [machow/quartodoc#386] [Q&A]
Documenting a python module, as example `sklearn.metrics` I get the name metrics twice.

How can I customize this to e.g. change the title to "Metrics" and hide the second `metrics`?

![image](https://github.com/user-attachments/assets/a6ec89c9-86fc-48e5-9a7d-6dc30d334849)

```yml
project:
  type: website

website:
  title: "Sklearn ripoff"

quartodoc:
  style: pkgdown
  package: sklearn

  sections:
    - title: Modules
      desc: ""
      contents:
        - name: metrics
          members: 
            - accuracy_score
            - r2_score
       
format:
  html:
    theme: cosmo

```
