### ISSUE TITLE
Enable basic interlinking of function names -> reference page

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#1]
Interlinking lets us take a reference to a function in a docstring (or qmd), and render it as a link to the function's documentation. This could be a link either within the current documentation (e.g. quartodoc docs) or across documentation sites (e.g. to python.org/docs).

**Key pieces:**

* generate a sphinx inventory file (or something similar)
* figure out a quarto strategy for interlinking (e.g. a filter?)

**Examples:**

* [plotnine geom_bar api doc](https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_bar.html#plotnine.geoms.geom_bar)
* [py-shiny page_fixed api doc](https://shiny.rstudio.com/py/api/reference/shiny.ui.page_fixed.html)

Note the "See Also" section, and links from annotations in these pages..

![image](https://user-images.githubusercontent.com/2574498/200365980-b3f13f1b-fae0-49b6-b464-8534cb0cbb32.png)

## Sphinx inventory files

A sphinx inventory file maps function names (or class member, etc..) to their internal pages on a documentation site. It is a sort-of gzipped file, and its structure is essentially:

* `"<object_type>": { <name>: <internal_url> }`

See this the [sphinx inventory case study](https://github.com/machow/quartodoc/blob/main/case_studies/sphinx-inventory.md) for how to read and use these files.

## Quarto interlinking

From what I've gathered, there are two ways we could do interlinking:

* when generating a qmd: quartodoc generates a reference page w/ links already generated. This would restrict us to interlinking only references in docstrings.
* during qmd rendering: quarto maybe could do interlinking through [filters](https://quarto.org/docs/extensions/filters.html)?

## Extra: how does pkgdown interlink?

[pkgdown](https://pkgdown.r-lib.org/) is an R package that can handle interlinking (note it does not use quarto).

It interlinks by the following strategy:

* generate a `_pkgdown.yml` file with with a reference section, that lists out all doc API functions.
* for crosslinking to other doc sites...
  - use `_pkgdown.yml` or the DESCRIPTION file to get the URL to the doc site
  - afaict assumes function docs have url of form: `{SITE_URL}/reference/{function_name}`. (e.g. see [this downlit code](https://github.com/r-lib/downlit/blob/d5622d665ebe4d3529b297aa926fe3c0132c8b81/R/metadata.R#L6))

**Comment by machow** [comment]
It sounds like quarto project level config (`_quarto.yml`) gets merged with document config, so we should be able to create a [quarto filter](https://quarto.org/docs/extensions/filters.html) that can be configured the same as intersphinx.

E.g. using [plotnine conf.py](https://github.com/has2k1/plotnine/blob/main/doc/conf.py#L408-L464) as an example, a quarto config might look like...

```yaml
interlink:
  sources:
    'python':
      url: 'https://docs.python.org/3/'
      inventory: null

    # probably also fine to use this as a shortcut for url field, with inventory null
    'matplotlib': 'https://matplotlib.org/stable'

    'numpy': 'https://numpy.org/doc/stable/'
    'scipy': 'https://docs.scipy.org/doc/scipy'
    'statsmodels': 'https://www.statsmodels.org/stable/'
    'pandas': 'https://pandas.pydata.org/pandas-docs/stable/'
    'sklearn': 'https://scikit-learn.org/stable/'
    'skmisc': 'https://has2k1.github.io/scikit-misc/stable/'
    'adjustText': 'https://adjusttext.readthedocs.io/en/latest/'
    'patsy': 'https://patsy.readthedocs.io/en/stable'

  # numpydoc interlinking options
  aliases:
    'Series': 'pandas.Series'
    'boolean': 'bool'
    'element_line': 'plotnine.themes.element_line'    

    # TODO: what's the equivalent to this?
    'position': ':term:`position`'
```

**Comment by machow** [comment]
See these jupyterbook docs:

* intersphinx linking using `[my link](content:references:labels)` ([docs page](https://jupyterbook.org/en/stable/content/references.html?highlight=link#reference-with-markdown-link-syntax))
* jupyter book config has an intersphinx_mapping field ([see this config](https://github.com/executablebooks/jupyter-book/blob/a2d441633d5aafed4e94bbc544183cf866213f3a/docs/_config.yml#L85))

Essentially if you have this in your config...

```yaml
intersphinx_mapping:
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
```

Then you can link like this to the myst-nb docs:

```
[check out myst-nb stdout](myst-nb:render/output/stdout-stderr)
```

The example above has these parts:

* content - myst-nb
* references - nb:render/output/stdout-stderr
* no labels specified
