### ISSUE TITLE
Support wildcards

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#118]
Similar to R's `{pkgdown}`, I'd like to use `startsWith("foo")` or a wild card `foo*` to signify anything that matches the pattern.

Ex:

I have 25 functions under `my_module` that I'd like displayed. It would be nice if I could say:

```yaml
quartodoc:
  style: pkgdown
  dir: reference
  package: mypkg
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - my_func
        - my_module.*
```

instead of 

```yaml
quartodoc:
  style: pkgdown
  dir: reference
  package: mypkg
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - my_func
        - my_module.func1
        - my_module.func2
        - my_module.func3
        - my_module.func4
        - my_module.func5
        - my_module.func6
        - ....
```

-------------------

This is low priority
