### ISSUE TITLE
Show sidenav reference in getting started `_quarto.yml`

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#137]
Ideally, you want a sidenav for the reference docs, should we include that in the getting starting guide, and point it at that?  I'm thinking this should be added to `_quarto.yml` 

```yml
website:
  sidebar: # see https://quarto.org/docs/reference/projects/websites.html#sidebar
      collapse-level: 2
      align: left
      contents: # see https://quarto.org/docs/websites/website-navigation.html#side-navigation
        - section: "Reference API"
          contents: "reference/**"
```
