### ISSUE TITLE
Should we add `quartodoc build` as a pre-render script in the suggested `_quarto.yml`? 

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#141]
I am not sure if there is a way to bake this behavior in as an extension (I think there should be?), but in the absence of that I think the below config is a big quality of life improvement if using quartodoc

See https://quarto.org/docs/projects/scripts.html#pre-and-post-render

WDYT?

```yaml
project:
  type: website
  pre-render:
    - "quartodoc build"
```
