### ISSUE TITLE
Fix content config Page example in getting started docs

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#143]
This example produces a pydantic validation error, since it's missing the .path field:

https://machow.github.io/quartodoc/get-started/basic-content.html#page-layout-element

```yaml
quartodoc:
  package: quartodoc
  sections:
    - title: Cool functions
      desc: ""

      # contents with a page grouping ----
      contents:
        - kind: page
          contents:
            - get_object
            - name: MdRenderer
              members: ["render"]
```

Related to #138 , maybe we make path optional and then give a much nicer error message then? In any event, we should fix the error and investigate custom pydantic validation / friendlier error messages.
