### ISSUE TITLE
Not able to document API `metaflow.current.Current`

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#144]
I'm trying to document [`metaflow.current.Current`](https://github.com/Netflix/metaflow/blob/master/metaflow/current.py), which has many properties nicely documented inside docstrings.  

However, none of those properties are documented by `quartodoc`

<img width="855" alt="image" src="https://github.com/machow/quartodoc/assets/1483922/cc756de0-7b1e-4c84-bf50-e2a6ecf8463a">

Here is my yaml

```yml
project:
  type: website
  pre-render:
    - "quartodoc build"

website:
  sidebar: # see https://quarto.org/docs/reference/projects/websites.html#sidebar
      collapse-level: 2
      align: left
      contents: # see https://quarto.org/docs/websites/website-navigation.html#side-navigation
        - section: "Reference API"
          contents: "reference/**"

quartodoc:
  package: metaflow
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - Flow
        - Run
        - current.Current
```

Quarto version: `1.4.25`
quartodoc version: `0.3.1`
