### ISSUE TITLE
validate all config pieces in the docs

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#145]
We should use quarto blocks with `#| include: false` to manually test individual examples of config blocks.

Related to #143 , where a piece of config on the content configuration page does not pass pydantic validation.

**Comment by machow** [comment]
May be easier to just use blocks like this...

``````
```{python}
#| output: asis
from quartodoc.docutils import validate

validate("""
quartodoc:
  package: quartodoc
  sections:
    - title: Some section
      desc: ""
      contents:
        - get_object        # function: quartodoc.get_object
        - ast.preview       # submodule func: quartodoc.ast.preview
        - MdRenderer        # class: quartodoc.MdRenderer
        - MdRenderer.render # method: quartodoc.MDRenderer.render
        - renderers         # module: quartodoc.renderers
""")
``````
