### ISSUE TITLE
Cannot document `pandas.read_csv` -> Griffe isn't able to access an object's docstring when its dynamically inserted? 

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#154]
IIUC griffe is having trouble with apis where the docstrings are dynamically inserted.  For example, let's take `pandas.read_csv`, the [docstring is dynamically added to this API](https://github.com/pandas-dev/pandas/blob/v2.0.1/pandas/io/parsers/readers.py#L814-L912)

```yaml
quartodoc:
  package: pandas
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - read_csv
```

The current tech is not able to parse the docstring.  

![image](https://github.com/machow/quartodoc/assets/1483922/907110bd-baa2-4b1f-a7f8-4ac3325146af)
