### ISSUE TITLE
Fix generated sidebar YAML

### ISSUE THREAD

**Issue by juliasilge** [machow/quartodoc#170]
As of now, the `_sidebar.yml` that is generated puts the sidebar on all pages, which doesn't make much sense. Instead, it should look like this:

```yaml
website:
  sidebar:
    - id: reference
      title: Function reference
      collapse-level: 2
      style: "floating"
      align: left
      contents:
      - reference/index.qmd
      - contents:
        - reference/board_folder.qmd
        - reference/board_local.qmd
        - reference/board_temp.qmd
        - reference/board_s3.qmd
        - reference/board_gcs.qmd
        - reference/board_azure.qmd
        - reference/board_connect.qmd
        - reference/board_url.qmd
        - reference/board.qmd
        section: Boards
      - contents:
        - reference/pin_read.qmd
        - reference/pin_write.qmd
        - reference/pin_meta.qmd
        - reference/pin_versions.qmd
        - reference/pin_list.qmd
        - reference/pin_exists.qmd
        - reference/pin_version_delete.qmd
        - reference/pin_versions_prune.qmd
        - reference/pin_delete.qmd
        - reference/pin_search.qmd
        section: Pins
```

**Comment by machow** [comment]
If I'm understanding correctly, the issue with the current sidebar is that the entry under sidebar is a mapping, when it it should be a list. Does that sound right?

**currently:** 

```yaml
website:
  sidebar:
    contents:
    - reference/index.qmd
    - contents:
      - ...
    id: reference
```

**should be:**

```yaml
website:
  sidebar:
    # note the leading -
    - contents:
      - reference/index.qmd
      - contents:
        - ...
      id: reference
```

I have no idea why this somehow worked with the documentation sites for shiny, siuba, and vetiver, but am guessing it has to do with them having another sidebar section (e.g. shiny's "learn shiny" pages) with sidebars (maybe due to the way quarto merges content).

**Comment by machow** [comment]
I am not able to remove the sidebar on the site index page by making the change. I was able to remove it by adding an additional dummy sidebar entry.

## Testing suggested change

Here is how I tested without the dummy entry (note that sidebar is still visible from index 😓).

**index.qmd**

```
---
---

I am a test page
```


**_quarto.yml**

```yaml
project:
  type: website

metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: quartodoc

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - get_object
        - preview
```

**_sidebar.yml**

```yaml
website:
  sidebar:
  - contents:
    - reference/index.qmd
    - contents:
      - reference/get_object.qmd
      - reference/preview.qmd
      section: Some functions
    id: reference
```

## Dummy entry

I was able to get the sidebar to disappear from the index page by adding this to `_quarto.yml`.

```
website:
  sidebar:
    - id: dummy
```

**Comment by juliasilge** [comment]
Oh, interesting, yep, I did have a something like this in my `_quarto.yml`:

```yaml
  sidebar:
    - id: test
```

OK, this does seem like a problem with Quarto which might be worth surfacing.

**Comment by juliasilge** [comment]
Ah, OK, I think there is special behavior if there is only one sidebar. This works fine:

```yaml
  sidebar:
    - id: dummy
    - id: reference
      title: Function reference
      collapse-level: 2
      style: "floating"
      align: left
      contents:
      - reference/index.qmd
      - contents:
        - reference/board_folder.qmd
        - reference/board_local.qmd
        - reference/board_temp.qmd
        - reference/board_s3.qmd
        - reference/board_gcs.qmd
        - reference/board_azure.qmd
        - reference/board_connect.qmd
        - reference/board_url.qmd
        - reference/board.qmd
        section: Boards
      - contents:
        - reference/pin_read.qmd
        - reference/pin_write.qmd
        - reference/pin_meta.qmd
        - reference/pin_download.qmd
        - reference/pin_upload.qmd
        - reference/pin_versions.qmd
        - reference/pin_list.qmd
        - reference/pin_exists.qmd
        - reference/pin_version_delete.qmd
        - reference/pin_versions_prune.qmd
        - reference/pin_delete.qmd
        - reference/pin_search.qmd
        section: Pins
```

While this shows up on all pages:

```yaml
  sidebar:
    - id: reference
      title: Function reference
      collapse-level: 2
      style: "floating"
      align: left
      contents:
      - reference/index.qmd
      - contents:
        - reference/board_folder.qmd
        - reference/board_local.qmd
        - reference/board_temp.qmd
        - reference/board_s3.qmd
        - reference/board_gcs.qmd
        - reference/board_azure.qmd
        - reference/board_connect.qmd
        - reference/board_url.qmd
        - reference/board.qmd
        section: Boards
      - contents:
        - reference/pin_read.qmd
        - reference/pin_write.qmd
        - reference/pin_meta.qmd
        - reference/pin_download.qmd
        - reference/pin_upload.qmd
        - reference/pin_versions.qmd
        - reference/pin_list.qmd
        - reference/pin_exists.qmd
        - reference/pin_version_delete.qmd
        - reference/pin_versions_prune.qmd
        - reference/pin_delete.qmd
        - reference/pin_search.qmd
        section: Pins
```
