### ISSUE TITLE
Support newer pkgdown title, subtitle, contents config

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#183]
Currently, we support the older style pkgdown configuration, where title, descriptions, and contents are a single entry:

```yaml
sections:
  - title: ""
    desc: ""
    contents:
      - ...
```

However, modern pkgdown uses a style more like this...

```yaml
sections:
  - title: ""
    desc: ""
  - subtitle: ""
  - contents:
    - ...
```

Notice that above, each piece is its own entry in the sections list. This makes it a bit easier to tack on a subtitle, etc..
