### ISSUE TITLE
Allowing fetching methods off classes when building

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#19]
Note the two commented out methods in the config below

```yaml
quartodoc:
  style: pkgdown
  dir: reference
  package: vetiver
  sections:
    - title: Deploy
      desc: ""
      contents:
        - VetiverAPI
        # NOTE: these pieces are methods on the VetiverAPI class
        # - VetiverAPI.run
        # - VetiverAPI.vetiver_post
        - vetiver_endpoint
        - predict
        - write_app
        - write_docker.write_docker
        - deploy_rsconnect
```
