### ISSUE TITLE
classes inside modules are not auto-rendering or being documenteed

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#197]
I'm trying to use quartodoc against bytewax in the `bytewax` branch of [this repo](https://github.com/hamelsmu/fastcore-quartodoc/blob/bytewax/_quarto.yml)

The quarto.yml file is like this:

```yaml
project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: bytewax

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: General utilities
      desc: General purpose utilities.
      dynamic: true
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - outputs
        - recovery
        - testing
    - title: Documentation utilities
      desc: Utilities for documentation.
      dynamic: true
      contents:
        - tracing
        - window
        - inputs

```

For example, there are many objects in the [outputs](https://github.com/bytewax/bytewax/blob/main/pysrc/bytewax/outputs.py) module, however that page doesn't contain anything and looks like this without any functions, or classes even though those exist in this module.

![image](https://github.com/machow/quartodoc/assets/1483922/6c578a83-d81a-4abd-8381-11f37fe1a81a)

You can repro this by checking out the `bytewax` branch of [this repo](https://github.com/hamelsmu/fastcore-quartodoc/blob/bytewax/_quarto.yml) and running `quartodoc build` followed by `quarto preview`
