### ISSUE TITLE
dynamic object introspection doesn't work

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#198]
I'm trying to dynamically document [modal.functions.web_endpoint](https://github.com/modal-labs/modal-client/blob/main/modal/functions.py#L1455).  Here is the yaml

```
project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: modal

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Documentation utilities
      desc: Utilities for documentation.
      dynamic: true
      contents:
        - functions.web_endpoint

 ```

In Ipython you can see the help just fine

```
In [4]: from modal.functions import web_endpoint

In [5]: ?web_endpoint
Signature:
web_endpoint(
    method: str = 'GET',
    label: Optional[str] = None,
    wait_for_response: bool = True,
) -> Callable[[Callable[..., Any]], modal.functions._PartialFunction]
Docstring:
Register a basic web endpoint with this application.

This is the simple way to create a web endpoint on Modal. The function
behaves as a [FastAPI](https://fastapi.tiangolo.com/) handler and should
return a response object to the caller.

Endpoints created with `@stub.web_endpoint` are meant to be simple, single
request handlers and automatically have
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) enabled.
For more flexibility, use `@stub.asgi_app`.

To learn how to use Modal with popular web frameworks, see the
[guide on web endpoints](https://modal.com/docs/guide/webhooks).

All webhook requests have a 150s maximum request time for the HTTP request itself. However, the underlying functions can
run for longer and return results to the caller on completion.

The two `wait_for_response` modes for webhooks are as follows:
* `wait_for_response=True` - tries to fulfill the request on the original URL, but returns a 302 redirect after ~150s to a result URL (original URL with an added `__modal_function_id=...` query parameter)
* `wait_for_response=False` - immediately returns a 202 ACCEPTED response with a JSON payload: `{"result_url": "..."}` containing the result "redirect" URL from above (which in turn redirects to itself every ~150s)
File:      /opt/anaconda3/lib/python3.9/site-packages/modal/functions.py
Type:      function
```

However nothing is rendered in `quartodoc`

![image](https://github.com/machow/quartodoc/assets/1483922/1e25b0d6-8b9a-442d-8279-8a7bec16c150)

To repro, checkout the `modal` branch of [this repo](https://github.com/hamelsmu/fastcore-quartodoc/tree/modal), and run `quartodoc build` followed by `quarto preview`

**Comment by machow** [comment]
quartodoc doesn't support dynamic being set to true on the section (though it could!), and pydantic unfortunately is happy to accept extra fields and then discard them 😬.

Does it work if you set dynamic at the top-level (right under quartodoc) or for the individual content entries?

https://machow.github.io/quartodoc/get-started/basic-docs.html#top-level-options

https://machow.github.io/quartodoc/get-started/basic-content.html#dynamic-lookup

I wonder if we can set pydantic to be strict and not silently drop extra fields 🤔

**Comment by hamelsmu** [comment]
If I set `dynamic: true` on the invidiual content entry, it still doesn't render properly.  Concretely, it doesn't show the signature

```yaml
project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: modal
  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Documentation utilities
      desc: Utilities for documentation.
      contents:
        - functions
        - name: web_endpoint
          contents: [functions.web_endpoint]
          dynamic: true
```

![image](https://github.com/machow/quartodoc/assets/1483922/2a0f3265-a88d-4f4d-bc77-40a066b8e75c)
