### ISSUE TITLE
Provide way for people to list documentation pages on sidebar

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#20]
Many python documentation sites also include their API doc pages on a sidebar, but this currently requires users do a lot of manual work. They can use quarto's options for [auto sidebar generation](https://quarto.org/docs/websites/website-navigation.html#auto-generation), but this only supports these two cases:

* contents are all laid flat on the sidebar
* contents are laid out in sections, by assuming each folder is a sidebar section

However, this means that sidebar layout and file directory structure are coupled. In practice, python documentation sites often lay out function pages flat in an API folder (e.g. [pandas.tseries.offsets.DateOffset.html](https://pandas.pydata.org/docs/reference/api/pandas.tseries.offsets.DateOffset.html)).

## Thoughts on fixes

* If quarto could decouple them (e.g. by allowing a sidebar config file, like `references/_sidebar.yml` etc..), then quartodoc could generate the sidebar config for references.
* quartodoc could add an option to output files in nested directories.
* quartodoc could print out the piece that users would paste into their `_quarto.yml`.

It seems like only the first will allow people to port their doc sites, without changing their structures. (Note also that the structure of python API sidebars generally does not correspond to package structure)

## Example 

For example, here is @isabelizimm's work on porting the vetiver docs to quartodoc. Notice that each section of the reference index page is also included on the sidebar.

![image](https://user-images.githubusercontent.com/2574498/213519396-d688ad64-7744-4744-be4f-81f1a16c39c8.png)

Currently, this must be done manually, by hard-coding the sidebar in `_quart.yml`:

```yaml
project:
  type: website

format:
  html:
    toc: true


website:
  title: "Vetiver API docs"
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference

  # note the duplication between sidebar and quartodoc fields
  #
  sidebar:
    - id: reference
      title: Reference
      contents:
        - section: Version
          contents:
            - reference/VetiverModel.qmd
            - reference/vetiver_pin_write.qmd
        # ...

quartodoc:
  style: pkgdown
  dir: reference
  package: vetiver
  sections:
    - title: "Version"
      desc: ""
      contents:
        - VetiverModel
        - vetiver_pin_write
      # ...
```

**Comment by machow** [comment]
I forgot that _metadata.yml in a folder gets include in docs, so maybe including a `reference/_metadata.yml` file, like this should work?:

```yaml
  sidebar:
    - id: reference
      title: Reference
      contents:
        - section: Version
          contents:
            - reference/VetiverModel.qmd
            - reference/vetiver_pin_write.qmd
        # ...
```
