### ISSUE TITLE
Summary page links do not include `.html`

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#201]
From: https://github.com/machow/quartodoc/blob/dd18915bd964ee26c11d912348ecf921d86a71a1/quartodoc/renderers/md_renderer.py#L548-L560

Ex: 

```
        - kind: page
          path: MyPage
          contents:
            - myfunc
```

Should link to `MyPage.html`, not `MyPage`
