### ISSUE TITLE
(interlinks) multiple references error when class as well as containing module have a page

### ISSUE THREAD

**Issue by jmbuhr** [machow/quartodoc#215]
Because of https://github.com/machow/quartodoc/issues/197  (classes in a module are not documented if just `- name: somemodule` is in the contents list),
I tried adding both the module as well as specifically classes in the module like:

```yml
quartodoc:
  package: package
  sidebar: _sidebar.yml
  style: pkgdown
  dir: reference

  sections:
    - title: Modules
      desc: Modules
      contents:
        - name: module
    - title: Things
      desc: Things
      contents:
        - name: module.SomeClass
```

This works to a page for the module and a page for the class, but fails as soon as interlinks e.g.

```
[](`package.module.SomeClass`)
```

are used:

```
Found multiple matches for package.module.SomeClass
1: table: 0x7fe828f3a740
  name: package.module.SomeClass
  role: class
  dispname: -
  domain: py
  priority: 1
  uri: /reference/module.html#package.module.SomeClass
2: table: 0x7fe828f3a740
  name: package.module.SomeClass
  role: class
  dispname: -
  domain: py
  priority: 1
  uri: /reference/module.SomeClass.html#package.module.SomeClass
```

In other words, the quartodoc interlinks filter sort of expects #174 to be implemented.

**Comment by machow** [comment]
Ah, sorry about this. I'm working on supporting class documentation inside modules in https://github.com/machow/quartodoc/pull/212. 

Is the ideal behavior for your case that documenting the module includes the class documentation? If so, #212 should hopefully resolve the issue.

Otherwise, does specifying the members explicitly for the module work for now? E.g.

```
      contents:
        - kind: auto
          name: Builder
          members:

            # specify the exact objects being documented on the module here ----

            - some_method
            - some_other_method
```
