### ISSUE TITLE
Support tilde (~) in config, to indicate short name should be used

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#230]
Currently, quartodoc allows users to set the `package:` field in order to shorten names. However, sphinx also allows the use of `~` to indicate that just the last part of a name should be used.

E.g. `~quartodoc.renderers.md_renderer.MdRenderer` -> `MdRenderer`

**Comment by has2k1** [comment]
In a project where some objects have the same name, for each object to get an api page, the objects as listed in the api page need different qualified (partial or full) names. Using a tilde allows us to keep the summary listing short and maintain the page disambiguation.

e.g. Below we have `plotnine.themes.themeable.dpi` and `plotnine.options.dpi` and using a tilde both can be summarised as `dpi` and have separate pages.

```yaml

    - subtitle: Themeables
      package: plotnine.themes.themeable
      contents:
        - aspect_ratio
        - axis_line
        - axis_line_x
        - axis_line_y
        - dpi                  # reference/dpi.html

    - subtitle: The Available Options
      desc: |
        These are _all_ the options that you can set or get the values of.
      package: plotnine.options
      contents:
        - current_theme
        - name: ~options.dpi   # reference/options.dpi.html
          package: plotnine

```
