### ISSUE TITLE
Simplify configuration of interlinks filter

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#24]
```yaml
interlinks:
  sources:

    # TODO: shouldn't *have* to specify your own site's objects.json
    quartodoc:
      url: "/"
      inv: null
      fallback: objects.json
    numpy:
      url: https://numpy.org/doc/stable/

      # TODO: fallback should be optional, with a sensible default
      fallback: _inv/objects_numpy.json
    python:
      url: https://docs.python.org/3/
      fallback: _inv/objects_python.json
```

Let's change to something like this:

```yaml
interlinks:
  # default
  cache: _inv

  # default
  site_inv: objects.json

  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      # optional
      inv: objects.inv
      url: https://docs.python.org/3/
```

Note that one sticking point, is we're assuming other docs are using `object.inv`. I think this makes sense, since quartodoc will need to export this format in order for other docs to interop anyway.
