### ISSUE TITLE
quartodoc interlinks should validate the version of the interlinks filter being used

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#259]
Currently, the `quartodoc interlinks` command doesn't check anything about the `interlinks` quarto filter installed. However, features like `quartodoc interlinks --fast` cannot run on old extension versions.

We should do two things:

* validate the filter version (e.g. that it will work correctly)
* orchestrate the installation of the filter

It's okay for now if we orchestrate by telling the user what to do. But let's investigate what managing / installing quarto extensions via the quartodoc CLI commands etc.. might look like.

**Comment by machow** [comment]
@cscheid, any idea how a program might check for a filter in the `_extensions` folder? 

If the interlinks filter has this `_extension.yml`:

```yaml
title: Interlinks
author: Michael Chow
version: 1.1.0
quarto-required: ">=1.2.0"
contributes:
  filters:
    - interlinks.lua
```

And it's path is...

```
_extensions/machow/interlinks/_extension.yml
```

What is used to determine the name? The final folder name (the "interlinks" in "machow/interlinks")?
