### ISSUE TITLE
Method table bleeds over the parent div width

### ISSUE THREAD

**Issue by cpcloud** [machow/quartodoc#267]
I'm seeing a method table [here](https://ibis-quarto.netlify.app/backends/bigquery) bleed outside the width of the rest of the contents in the parent div.

When I scroll far enough the TOC on the right side of the page is obscured by the method table:

![image](https://github.com/machow/quartodoc/assets/417981/bccd1fed-8d94-4bfe-96e6-9e777036cab9)

**Comment by cpcloud** [comment]
We ended up working around this with a bit of custom CSS: https://github.com/ibis-project/ibis/pull/7048

**Comment by machow** [comment]
Thanks for flagging, and finding a workaround. I'm going to paste the css that fixed it here:

```css
section#connection-parameters {
    /* scroll when child contents overflow the width */
    overflow-x: auto;
}
```

cc @cscheid, do you know if this might be a quarto issue (or maybe tables bleeding over is a general html + css quirk that users may just need to workaround)?

**Comment by cpcloud** [comment]
We ended up with a slightly different block of css to accommodate multiple parameters tables on the same API docs page:

```css
section#parameters {
    /* scroll when child contents overflow the width */
    overflow-x: auto;
}

section[id^="parameters-"] {
    /* scroll when child contents overflow the width */
    overflow-x: auto;
}
```

**Comment by cscheid** [comment]
@dragonstyle is the HTML format+style expert, he will know better than me for sure.

**Comment by cpcloud** [comment]
@dragonstyle Thanks for clarifying.

> You should be able to remember this simply by more explicitly allowing the table to overflow into the margin

Can you elaborate a bit on this? Is what you're describing different from the current behavior?

**Comment by machow** [comment]
If I'm understanding the original example, here's a tiny example reproducing the table overflow. It looks like less of a TOC issue, and more of a weird table html behavior?

**_quarto.yml**

```yaml
project:
  type: website

website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - file: index.qmd

format:
  html:
    toc: true
```

**index.qmd**

```
---
---


## Some section

| a | 
| --- |
| aabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabcaabcabcabcabcabcabc |
```

The table overflows its container, because there's are no spaces in its content.

<img width="1692" alt="image" src="https://github.com/machow/quartodoc/assets/2574498/a1c6f89c-eb2e-4171-9239-5ed09711c83d">
