### ISSUE TITLE
Automatically generating documentation

### ISSUE THREAD

**Issue by JanPalasek** [machow/quartodoc#275]
Hello. Can I generate documentation automatically from the source code? Similar to what [pdoc3](https://pdoc3.github.io/pdoc/) does.

**Comment by machow** [comment]
Hey, thanks for raising! I wonder if you could get something similar by enumerating just the modules in your package? For example...

```yaml
quartodoc:
  package: PACKAGE_NAME
  sections:
    - contents:
        # document the top level package
        - SOME_MODULE
        - ANOTHER_MODULE
```

Right now, documenting the top-level module is a bit funky, but can be done using...

```yaml
quartodoc:
  sections:
    - contents:
        # document the top level package
        - name: PACKAGE_NAME
          package: null
          # includes classes and functions imported from submodules
          # this shouldn't be enabled if you are documenting the submodules themselves
          include_imports: true
```

Is there any chance you could point me to the package you're looking to document? I'm familiar with pdoc, but haven't seen it used extensively, so am curious to try it out! It seems useful to try and fit quartodoc to this use-case!
