### ISSUE TITLE
Project Type: Book (Fix Broken Links)

### ISSUE THREAD

**Issue by s2t2** [machow/quartodoc#346]
Hi, this auto-documentation feature is awesome, and works great for me when I am using a "website" quarto project type.

However when I use the "book" quarto project type, I notice the index table shows up, but the links no longer work, and the linked content doesn't show up in the book PDF either.

I was wondering if you have any guidance about getting quartodoc to work with the ["book" project type](https://quarto.org/docs/books/).

I think there may be an issue with the links pointing to .qmd instead of .html, and also the .html files not getting generated.

Thank you!

### Book Project Type

Here is my quarto config yml file for book project type:

```yml
project:
  type: book

book:
  title: "My Quarto Book"
  author: "Your Name Here"
  date: "6/10/2024"
  chapters:
    - index.qmd
    - about.qmd
    - article.md
    - python-example.qmd
    - demo-notebook.ipynb
    - reference/index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png

quartodoc:
  package: my_project
  dir: reference
  sections:
    - title: Some functions
      desc: Functions to exemplify auto documentation.
      contents:
        - calculator.Calculator
        - formatter.to_usd

```

Broken links with "book" project type (seems like href points to a .qmd file instead of .html file):

<img width="1149" alt="Screenshot 2024-06-10 at 1 23 25 PM" src="https://github.com/machow/quartodoc/assets/1328807/4b372002-bbfb-4283-b94f-63c6f90d1b80">
<img width="914" alt="Screenshot 2024-06-10 at 1 23 41 PM" src="https://github.com/machow/quartodoc/assets/1328807/c891e584-c44b-45a3-81d9-424d81e13dd9">

Here is my generated "reference/index.qmd" file with links to the autodocumentation pages:

```md
# Function reference {.doc .doc-index}

## Some functions

Functions to exemplify auto documentation.

| | |
| --- | --- |
| [calculator.Calculator](calculator.Calculator.qmd#my_project.calculator.Calculator) | The Calculator class. Use for basic math. |
| [formatter.to_usd](formatter.to_usd.qmd#my_project.formatter.to_usd) | Formats number as USD with dollar sign, two decimal places, and thousands separator. |
```

Looks like when I build the autodocumentation, the corresponding HTML pages (e.g. "reference/calculator.Calculator.qmd") no longer get generated to "_book/reference" directory. There is just the "reference/index.qmd" file in there.

### Website Project Type

Here was my working quarto config yml for a website project type:

```yml
project:
  type: website
  output-dir: _build

website:
  title: "This is a site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.md
      - python-example.qmd
      - demo-notebook.ipynb
      - reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: my_project
  dir: reference
  sections:
    - title: Some functions
      desc: Functions to exemplify auto documentation.
      contents:
        - calculator.Calculator
        - formatter.to_usd
      
```

Working links with "website" project type:

<img width="988" alt="Screenshot 2024-06-10 at 1 22 52 PM" src="https://github.com/machow/quartodoc/assets/1328807/564bfd7b-e604-4f3f-926e-d45cff16a0a1">
<img width="1177" alt="Screenshot 2024-06-10 at 1 23 00 PM" src="https://github.com/machow/quartodoc/assets/1328807/a9e4855a-fe00-400b-908d-760f878bf45a">

**Comment by machow** [comment]
Hmm.. I'm not sure what's happening. I created a small book example, with some quartodoc items in the reference, and it seemed to work okay when I ran...

```bash
quartodoc build
quarto preview
```

Here's what I used (note I left in the generated reference folder):

[book.zip](https://github.com/user-attachments/files/15777393/book.zip)

**Comment by s2t2** [comment]
Hi @machow I appreciate the reply.

I cleared the references directory and re-ran the following commands, but unfortunately the links are still broken.

```sh
quartodoc build --config docs/_quarto.yml
quarto render docs/
```


My quarto version is `1.4.554`.

My code is in this [PR](https://github.com/s2t2/quarto-book-template/pull/2/files).

**Comment by machow** [comment]
shoot, exploring a bit more -- I wonder if quarto books require the things being linked to to be listed in chapters? When I add the API Reference pages to `chapters:` I'm able to click the links and see the rendered HTML.

So for example adding this to `_quarto.yml`...

```yaml
book:
  title: "My Quarto Book"
  author: "Your Name Here"
  date: "6/10/2024"
  chapters:
    - index.qmd
    - reference/index.qmd

    # Added this page ----
    - reference/MdRenderer.qmd
```
