### ISSUE TITLE
Bread-crumbs 

### ISSUE THREAD

**Issue by peekxc** [machow/quartodoc#355]
I'm having trouble generating bread-crumbs on a quartodoc-based site I'm working on. 

Namely, setting the following option in the `_quarto.yml` file does nothing for me: 
```{yaml}
website:
  bread-crumbs: true
```

Interestingly, manually adding the option to the attribute at the top of each qmd page seems to work so long as the title is also included, e.g.

```md
---
title: cover.set_cover_greedy
bread-crumbs: true
---
... // Note: normal H1 header needs to be removed here
```
According to the [quarto docs](https://quarto.org/docs/websites/website-navigation.html#breadcrumbs), bread-crumb generation should be default behavior, yet 
they don't show in e.g. the vetiver docs even though [they aren't specified](https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml). This leads to me to believe that maybe it's a quartdoc issue (it might be a quarto one though). 

According to the [docs](https://quarto.org/docs/websites/website-navigation.html#breadcrumbs): 

> By default, navigational breadcrumbs are displayed above the page title on each page that is nested deeper than one level in the sidebar navigation.

For reference, here's what breadcrumbs look like when they show up

<img width="998" alt="Screenshot 2024-08-05 at 4 44 31 PM" src="https://github.com/user-attachments/assets/8dab19a4-1c2d-4536-a68f-db3f76fa7826">

vs they don't: 

<img width="1014" alt="Screenshot 2024-08-05 at 4 44 42 PM" src="https://github.com/user-attachments/assets/6e454555-f2e0-4ca8-9495-8e61bfe79c83">

My sidebar.yml is quite uniform and meets the requirements I believe: 

```yml
website:
  sidebar:
  - contents:
    - name: Geomcover
      href: ./index.qmd
    - section: Set Cover (`cover`)
      contents:
        - ./cover.coverage.qmd
        - ./cover.valid_cover.qmd
        - ./cover.set_cover_greedy.qmd
        - ./cover.set_cover_rr.qmd
        - ./cover.set_cover_ilp.qmd
        - ./cover.set_cover_sat.qmd
    - section: Linear Algebra (`linalg`)
      contents:
        - ./linalg.pca.qmd
        - ./linalg.cmds.qmd      
    - section: Geometry (`geometry`)
      contents:
        - ./geometry.tangent_bundle.qmd
        - ./geometry.bundle_weights.qmd
    - section: I/O (`io`)
      contents:
        - ./io.load_set_cover.qmd
        - ./io.to_canonical.qmd
        - ./io.sets_to_sparse.qmd
        - ./io.sparse_to_sets.qmd
        - ./io.reindex_sparse.qmd
    id: .
  - id: dummy-sidebar
```

(Here's my [source code](https://github.com/peekxc/geomcover))
