### ISSUE TITLE
Add check to ensure all functions are included in the reference?

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#80]
From @GShotwell

> Is it possible to add some kind of check to ensure that all the functions are included in the reference? In pkgdown you can do this with a miscellaneous grouping which is useful for when people forget to update the site metadata when they add a feature.

This sounds like it could be handy! Any chance you can point to an example / docs of this? I'm a bit rusty on pkgdown..

**Comment by machow** [comment]
It sounds like it may be related to pkgdown allowing tidyselection:

```
- title: Superseded
  desc: >
    ...
  contents:
  - ends_with("_at")
```

https://github.com/tidyverse/dplyr/blob/main/_pkgdown.yml#L122
