### ISSUE TITLE
Should be able to set `dynamic: true` project-wide

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#94]

**Comment by machow** [comment]
Currently, people must specify dynamic per item, like so...

```yaml
    - title: Docstring Renderers
      desc: |
        Renderers convert parsed docstrings into a target format, like markdown.
      contents:
        - name: MdRenderer
          children: linked
        - name: MdRenderer.render
          dynamic: true
```

This change will make it less verbose for sites where everything is dynamic. I do think we want to discourage people from setting dynamic out of the gate, since the mechanisms for dynamic introspection are fairly new in quartodoc.
