### ISSUE TITLE
Objects from another package don't seem to work in nested `contents`

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#95]
For example, this works for `package: shiny`:

```
    - title: Types
      desc: ""
      contents:
        - kind: page
          path: MiscTypes
          flatten: true
          contents:
            - types.FileInfo
            - types.ImgData
    - title: htmltools Tag types
      desc: ""
      package: null
      contents:
        - htmltools.Tag
        - htmltools.TagAttrs
        - htmltools.TagAttrValue
        - htmltools.TagChild
        - htmltools.TagList
```

However, this does not:

```
    - title: Types
      desc: ""
      contents:
        - kind: page
          path: MiscTypes
          flatten: true
          contents:
            - types.FileInfo
            - types.ImgData
        - kind: page
          path: Tag
          flatten: true
          contents:
            - htmltools.Tag
            - htmltools.TagAttrs
            - htmltools.TagAttrValue
            - htmltools.TagChild
            - htmltools.TagList
```

**Comment by machow** [comment]
We resolved this by setting package: null

```
        - kind: page
          path: Tag

          # added this field
          package: null

          flatten: true
          contents:
            - htmltools.Tag
            - htmltools.TagAttrs
            - htmltools.TagAttrValue
            - htmltools.TagChild
            - htmltools.TagList
```
